add rebar upgrade script.
Add rebar upgrade script to manage upgrades of rcouch nodes.

diff --git a/rel/files/rcouch b/rel/files/rcouch
--- a/rel/files/rcouch
+++ b/rel/files/rcouch
@@ -224,8 +224,29 @@ case "$1" in
     uris)
         $NODETOOL rpc couch_httpd display_uris
         ;;
+    upgrade)
+        if [ -z "$2" ]; then
+            echo "Missing upgrade package argument"
+            echo "Usage: $SCRIPT upgrade {package base name}"
+            echo "NOTE {package base name} MUST NOT include the .tar.gz suffix"
+            exit 1
+        fi
+
+        # Make sure a node IS running
+        RES=`$NODETOOL ping`
+        ES=$?
+        if [ "$ES" -ne 0 ]; then
+            echo "Node is not running!"
+            exit $ES
+        fi
+
+        node_name=`echo $NAME_ARG | awk '{print $2}'`
+        erlang_cookie=`echo $COOKIE_ARG | awk '{print $2}'`
+
+        $ERTS_PATH/escript $RUNNER_BASE_DIR/bin/install_upgrade.escript $node_name $erlang_cookie $2
+        ;;
     *)
-        echo "Usage: $SCRIPT {start|start_front|stop|restart|reboot|ping|console|console_clean|attach|uris}"
+        echo "Usage: $SCRIPT {start|start_front|stop|restart|reboot|ping|console|console_clean|attach|upgrade|uris}"
         exit 1
         ;;
 esac
